### ISSUE TITLE
Test API

### ISSUE THREAD

**Issue by LBeghini** [WS22-23-SWEPM3ILV-INF-BA-VZ-Group-2/API#21]
Follow the [README.md](https://github.com/WS22-23-SWEPM3ILV-INF-BA-VZ-Group-2/API/blob/main/README.md) setup to run the project.

Assure that:

- [x] README is complete and easy to understand
- [ ] Code does not raise errors
- [ ] A message is seeing accessing url http://localhost:8080/

**Comment by anisharoy0304** [comment]
README is easy to understand. However, when doing ' npm install --save ' an error is raised as no package.json file exists yet. When trying to execute ' node server.js ' - MODULE NOT FOUND error is raised.

The server is unable to run, thus http://localhost:8080/ cannot be accessed.

A screenshot of both errors raised is attached.



![Image](https://user-images.githubusercontent.com/100205789/203613759-a261733a-b126-4206-ac28-89bec0f11075.png)

**Comment by anisharoy0304** [comment]
EDIT: As the group has decided to use the Django REST Framework for the backend, this method of testing the API (as well as the README file) is no longer valid. A new issue for testing the API can be created once a Django project has been created.

**Comment by LBeghini** [comment]
@anisharoy0304 yes, indeed this tests is no longer valid. However (probably because missing on the README) the root folder does not have the file `server.js` nor the `package.json`, being necessary to, first change the directory to the correct one:
```
cd node-js-express-login--mongodb
``` 

And then `npm install`. That is why you got that error. 
But either way, the application would not work as @MelvinPariyadan saw yesterday because of the missing database that were not configured nor have the necessary keys.
